[build]
  publish = "dist"
  command = "npm run build"

[forms]
  [forms.beta-access]
    name = "beta-access"
    
[dev]
  framework = "vite"

[redirects]
  from = "/*"
  to = "/index.html"
  status = 200